# Generated by Django 4.1.1 on 2022-09-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_path',
            new_name='image',
        ),
    ]
