# Generated by Django 4.1.1 on 2022-09-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_image_path_user_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
