# Generated by Django 4.1.1 on 2022-09-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_follow_requests_alter_page_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_blocked_permanently',
            field=models.BooleanField(default=False, verbose_name='Is page blocked permanently'),
        ),
    ]
