# Generated by Django 4.1.1 on 2022-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_is_blocked_permanently'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Page description'),
        ),
    ]
