# Generated by Django 4.1.1 on 2022-09-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_page_image_path_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Page image path'),
        ),
    ]
