# Generated by Django 4.1.1 on 2022-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_page_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(related_name='pages', to='pages.tag', verbose_name='Page tags'),
        ),
    ]
